source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-geometry-zsh-SLASH-geometry/geometry.plugin.zsh
source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-desyncr-SLASH-geometry-dir-info-prompt/plugin.zsh
source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zuxfoucault-SLASH-colored-man-pages_mod/colored-man-pages_mod.plugin.zsh
source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-history-substring-search/zsh-history-substring-search.plugin.zsh
source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-b4b4r07-SLASH-enhancd/init.sh
source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-RobSis-SLASH-zsh-completion-generator/zsh-completion-generator.plugin.zsh
source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-sharat87-SLASH-zsh-vim-mode/zsh-vim-mode.plugin.zsh
source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/plugins/git/git.plugin.zsh
source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh
source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/plugins/python/python.plugin.zsh
source /home/umi/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/plugins/stack/stack.plugin.zsh
