export ZSH=$HOME/.oh-my-zsh

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH

# Path to your oh-my-zsh installation.

export EDITOR=nvim
export VISUAL=nvim

# Better ls
export DISABLE_LS_COLORS="true"
export LS_COLORS=$(ls_colors_generator)
run_ls() {
	ls-i --color=auto -w $(tput cols) "$@"
}

run_dir() {
	dir-i --color=auto -w $(tput cols) "$@"
}

run_vdir() {
	vdir-i --color=auto -w $(tput cols) "$@"
}
alias ls="run_ls"
alias dir="run_dir"
alias vdir="run_vdir"

#GPG stuff
export GPG_TTY=$(tty)
export GPG_AGENT_INFO=""
eval $(keychain --eval -Q --quiet id_dsa id_rsa)

# add Cabal's bin directory to the executable search PATH if it exists
if [ -d "$HOME/.cabal/bin" ] ; then
    export PATH="$HOME/.cabal/bin:$PATH"
fi

# add Stack's bin directory to the executable search PATH if it exists
if [ -d "$HOME/.local/bin" ] ; then
    export PATH="$HOME/.local/bin:$PATH"
fi 

# Theme
ZSH_THEME="lambda-mod"

# Auto-correction.
ENABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-ff"

# Plugins
plugins=(git python fancy-ctrl-z thefuck wd stack vi-mode z)


# Evals
eval $(thefuck --alias fuck)

# Alias
alias zshrc='nvim ~/.zshrc'
alias vimrc='nvim ~/dotfiles/neovim/init.vim'
alias reload='source ~/.zshrc'
alias sudo='sudo '
alias rurisay='cowsay -f ~/scripts/ruri.cow'
alias rurithink='cowthink -f ~/scripts/ruri_think.cow'
alias pp='git pull; git push'
alias gdbstack='gdb --batch --ex r --ex bt --ex q --args'
alias ghci='python3 ~/scripts/ghci_prompt.py'
alias vim='nvim'
alias vi='nvim'
alias die='shutdown now'
alias coala='~/venv/coala/bin/coala'
if [ -z "$TMUX" ]; then task; fi

source $ZSH/oh-my-zsh.sh

# OS dependent config
if [ `uname` = 'Linux' ]; then # Linux
    export PATH="${HOME}/.gem/ruby/2.5.0/bin:$PATH"
    alias buku='~/venv/buku/bin/buku'
    alias aur='pacaur'
    alias yolo='pacaur -Syu;bash ~/scripts/update_quarter_tiling.sh'
    alias pac-optimize='sudo pacman -Sc; sudo pacman-optimize'
    alias pac-orphans='sudo pacman -Rns $(pacman -Qtdq)'
    alias pac-mirror='sudo pacman-mirrors -f 0 && sudo pacman -Syy'
    alias open='xdg-open'
else # Macos
    export PATH="/usr/local/opt/llvm/bin:/usr/local/bin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    export LS_COLORS=$(ls_colors_generator)
    export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
    alias gcc='gcc-7'
    alias cc='gcc-7'
    alias yolo='brew update; brew upgrade; brew cask upgrade; brew cleanup; brew cask cleanup;' 
fi
