fpath+=~/.zfunc
export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH
autoload -Uz compinit; compinit -iCd $HOME/.zcompdump
zstyle ':completion:*' menu select

# OS dependent config
if [ `uname` != 'Linux' ]; then # macOS
    export PATH="/usr/local/opt/qt/bin:/usr/local/opt/llvm/bin:/usr/local/bin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
fi

# nvim
if [[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]]; then
  source "${VIRTUAL_ENV}/bin/activate"
fi

GEOMETRY_PROMPT_PLUGINS=(virtualenv exec_time git jobs rustup)
for x in $HOME/dotfiles/shell/*.zsh; do source $x; done
source $HOME/.plugins.zsh

export EDITOR=nvim
export VISUAL=nvim
export PAGER=nvimpager

#GPG stuff
export GPG_TTY=$(tty)
export GPG_AGENT_INFO=""
if [ `uname` = 'Linux' ]; then
    eval $(keychain --eval -Q --quiet id_dsa id_rsa);
fi

# startup
if [ -z "$TMUX" ]; then
    if [ `uname` != 'Linux' ] || [ `basename '/'$(ps -f -p $(cat /proc/$(echo $$)/stat | cut -d \  -f 4) | tail -1 | sed 's/^.* //')` != "yakuake" ]; then
        curl -s wttr.in/Toronto | head -n 17;
    fi
    task;
fi

source $HOME/private.zsh
