base_exec_before = """
from pathlib import Path
import collections
from collections import Counter
"""

[[command]]
name = "glob"
help = "Glob over a directory"
arguments = [{name="pattern", type="str"}]
inject_values=["pattern"]

    [[command.stages]]
    command = "eval"
    params = {code="glob.glob(pattern)"}

    [[command.stages]]
    command = "chain"
