#!/bin/sh

#
# ~/.xsession
#
# Executed by xdm/gdm/kdm at login
#

export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_PLUGIN_PATH=$HOME/.kde4/lib/kde4/plugins/:/usr/lib/kde4/plugins/
XDG_CURRENT_DESKTOP=KDE
export DESKTOP_SESSION=kde
# fix mpd
python3 $HOME/dotfiles/music/mpd/mpd.py 'DigiHug USB Audio' &

# Merge colors and settings
xrdb ~/.Xresources &

xrandr --output HDMI-0 --auto --output DVI-I-1 --auto --left-of HDMI-0 --output DP-3 --auto --right-of HDMI-0 &
feh --bg-scale ~/dotfiles/wallpapers/0.jpg ~/dotfiles/wallpapers/1.jpg ~/dotfiles/wallpapers/2.jpg &
jetbrains-toolbox &
nextcloud &
yakuake &
xmodmap "$HOME/.Xmodmap" &
mpd &
